import torch

path = 'checkpoints/512/550000_net_G.pth'
model = torch.load(path)
for key, val in model.items():
    print(key)
'''
first_layer.1.weight
first_layer.1.bias
first_layer.2.weight
first_layer.2.bias
first_layer.2.running_mean
first_layer.2.running_var
first_layer.2.num_batches_tracked
down0.0.weight
down0.0.bias
down0.1.weight
down0.1.bias
down0.1.running_mean
down0.1.running_var
down0.1.num_batches_tracked
down1.0.weight
down1.0.bias
down1.1.weight
down1.1.bias
down1.1.running_mean
down1.1.running_var
down1.1.num_batches_tracked
down2.0.weight
down2.0.bias
down2.1.weight
down2.1.bias
down2.1.running_mean
down2.1.running_var
down2.1.num_batches_tracked
down3.0.weight
down3.0.bias
down3.1.weight
down3.1.bias
down3.1.running_mean
down3.1.running_var
down3.1.num_batches_tracked
BottleNeck.0.conv1.1.weight
BottleNeck.0.conv1.1.bias
BottleNeck.0.style1.linear.weight
BottleNeck.0.style1.linear.bias
BottleNeck.0.style1.conv_ada1.weight
BottleNeck.0.style1.conv_ada1.bias
BottleNeck.0.style1.bn_ada1.weight
BottleNeck.0.style1.bn_ada1.bias
BottleNeck.0.style1.bn_ada1.running_mean
BottleNeck.0.style1.bn_ada1.running_var
BottleNeck.0.style1.bn_ada1.num_batches_tracked
BottleNeck.0.style1.conv_ada2.weight
BottleNeck.0.style1.conv_ada2.bias
BottleNeck.0.conv2.1.weight
BottleNeck.0.conv2.1.bias
BottleNeck.0.style2.linear.weight
BottleNeck.0.style2.linear.bias
BottleNeck.0.style2.conv_ada1.weight
BottleNeck.0.style2.conv_ada1.bias
BottleNeck.0.style2.bn_ada1.weight
BottleNeck.0.style2.bn_ada1.bias
BottleNeck.0.style2.bn_ada1.running_mean
BottleNeck.0.style2.bn_ada1.running_var
BottleNeck.0.style2.bn_ada1.num_batches_tracked
BottleNeck.0.style2.conv_ada2.weight
BottleNeck.0.style2.conv_ada2.bias
BottleNeck.1.conv1.1.weight
BottleNeck.1.conv1.1.bias
BottleNeck.1.style1.linear.weight
BottleNeck.1.style1.linear.bias
BottleNeck.1.style1.conv_ada1.weight
BottleNeck.1.style1.conv_ada1.bias
BottleNeck.1.style1.bn_ada1.weight
BottleNeck.1.style1.bn_ada1.bias
BottleNeck.1.style1.bn_ada1.running_mean
BottleNeck.1.style1.bn_ada1.running_var
BottleNeck.1.style1.bn_ada1.num_batches_tracked
BottleNeck.1.style1.conv_ada2.weight
BottleNeck.1.style1.conv_ada2.bias
BottleNeck.1.conv2.1.weight
BottleNeck.1.conv2.1.bias
BottleNeck.1.style2.linear.weight
BottleNeck.1.style2.linear.bias
BottleNeck.1.style2.conv_ada1.weight
BottleNeck.1.style2.conv_ada1.bias
BottleNeck.1.style2.bn_ada1.weight
BottleNeck.1.style2.bn_ada1.bias
BottleNeck.1.style2.bn_ada1.running_mean
BottleNeck.1.style2.bn_ada1.running_var
BottleNeck.1.style2.bn_ada1.num_batches_tracked
BottleNeck.1.style2.conv_ada2.weight
BottleNeck.1.style2.conv_ada2.bias
BottleNeck.2.conv1.1.weight
BottleNeck.2.conv1.1.bias
BottleNeck.2.style1.linear.weight
BottleNeck.2.style1.linear.bias
BottleNeck.2.style1.conv_ada1.weight
BottleNeck.2.style1.conv_ada1.bias
BottleNeck.2.style1.bn_ada1.weight
BottleNeck.2.style1.bn_ada1.bias
BottleNeck.2.style1.bn_ada1.running_mean
BottleNeck.2.style1.bn_ada1.running_var
BottleNeck.2.style1.bn_ada1.num_batches_tracked
BottleNeck.2.style1.conv_ada2.weight
BottleNeck.2.style1.conv_ada2.bias
BottleNeck.2.conv2.1.weight
BottleNeck.2.conv2.1.bias
BottleNeck.2.style2.linear.weight
BottleNeck.2.style2.linear.bias
BottleNeck.2.style2.conv_ada1.weight
BottleNeck.2.style2.conv_ada1.bias
BottleNeck.2.style2.bn_ada1.weight
BottleNeck.2.style2.bn_ada1.bias
BottleNeck.2.style2.bn_ada1.running_mean
BottleNeck.2.style2.bn_ada1.running_var
BottleNeck.2.style2.bn_ada1.num_batches_tracked
BottleNeck.2.style2.conv_ada2.weight
BottleNeck.2.style2.conv_ada2.bias
BottleNeck.3.conv1.1.weight
BottleNeck.3.conv1.1.bias
BottleNeck.3.style1.linear.weight
BottleNeck.3.style1.linear.bias
BottleNeck.3.style1.conv_ada1.weight
BottleNeck.3.style1.conv_ada1.bias
BottleNeck.3.style1.bn_ada1.weight
BottleNeck.3.style1.bn_ada1.bias
BottleNeck.3.style1.bn_ada1.running_mean
BottleNeck.3.style1.bn_ada1.running_var
BottleNeck.3.style1.bn_ada1.num_batches_tracked
BottleNeck.3.style1.conv_ada2.weight
BottleNeck.3.style1.conv_ada2.bias
BottleNeck.3.conv2.1.weight
BottleNeck.3.conv2.1.bias
BottleNeck.3.style2.linear.weight
BottleNeck.3.style2.linear.bias
BottleNeck.3.style2.conv_ada1.weight
BottleNeck.3.style2.conv_ada1.bias
BottleNeck.3.style2.bn_ada1.weight
BottleNeck.3.style2.bn_ada1.bias
BottleNeck.3.style2.bn_ada1.running_mean
BottleNeck.3.style2.bn_ada1.running_var
BottleNeck.3.style2.bn_ada1.num_batches_tracked
BottleNeck.3.style2.conv_ada2.weight
BottleNeck.3.style2.conv_ada2.bias
BottleNeck.4.conv1.1.weight
BottleNeck.4.conv1.1.bias
BottleNeck.4.style1.linear.weight
BottleNeck.4.style1.linear.bias
BottleNeck.4.style1.conv_ada1.weight
BottleNeck.4.style1.conv_ada1.bias
BottleNeck.4.style1.bn_ada1.weight
BottleNeck.4.style1.bn_ada1.bias
BottleNeck.4.style1.bn_ada1.running_mean
BottleNeck.4.style1.bn_ada1.running_var
BottleNeck.4.style1.bn_ada1.num_batches_tracked
BottleNeck.4.style1.conv_ada2.weight
BottleNeck.4.style1.conv_ada2.bias
BottleNeck.4.conv2.1.weight
BottleNeck.4.conv2.1.bias
BottleNeck.4.style2.linear.weight
BottleNeck.4.style2.linear.bias
BottleNeck.4.style2.conv_ada1.weight
BottleNeck.4.style2.conv_ada1.bias
BottleNeck.4.style2.bn_ada1.weight
BottleNeck.4.style2.bn_ada1.bias
BottleNeck.4.style2.bn_ada1.running_mean
BottleNeck.4.style2.bn_ada1.running_var
BottleNeck.4.style2.bn_ada1.num_batches_tracked
BottleNeck.4.style2.conv_ada2.weight
BottleNeck.4.style2.conv_ada2.bias
BottleNeck.5.conv1.1.weight
BottleNeck.5.conv1.1.bias
BottleNeck.5.style1.linear.weight
BottleNeck.5.style1.linear.bias
BottleNeck.5.style1.conv_ada1.weight
BottleNeck.5.style1.conv_ada1.bias
BottleNeck.5.style1.bn_ada1.weight
BottleNeck.5.style1.bn_ada1.bias
BottleNeck.5.style1.bn_ada1.running_mean
BottleNeck.5.style1.bn_ada1.running_var
BottleNeck.5.style1.bn_ada1.num_batches_tracked
BottleNeck.5.style1.conv_ada2.weight
BottleNeck.5.style1.conv_ada2.bias
BottleNeck.5.conv2.1.weight
BottleNeck.5.conv2.1.bias
BottleNeck.5.style2.linear.weight
BottleNeck.5.style2.linear.bias
BottleNeck.5.style2.conv_ada1.weight
BottleNeck.5.style2.conv_ada1.bias
BottleNeck.5.style2.bn_ada1.weight
BottleNeck.5.style2.bn_ada1.bias
BottleNeck.5.style2.bn_ada1.running_mean
BottleNeck.5.style2.bn_ada1.running_var
BottleNeck.5.style2.bn_ada1.num_batches_tracked
BottleNeck.5.style2.conv_ada2.weight
BottleNeck.5.style2.conv_ada2.bias
BottleNeck.6.conv1.1.weight
BottleNeck.6.conv1.1.bias
BottleNeck.6.style1.linear.weight
BottleNeck.6.style1.linear.bias
BottleNeck.6.style1.conv_ada1.weight
BottleNeck.6.style1.conv_ada1.bias
BottleNeck.6.style1.bn_ada1.weight
BottleNeck.6.style1.bn_ada1.bias
BottleNeck.6.style1.bn_ada1.running_mean
BottleNeck.6.style1.bn_ada1.running_var
BottleNeck.6.style1.bn_ada1.num_batches_tracked
BottleNeck.6.style1.conv_ada2.weight
BottleNeck.6.style1.conv_ada2.bias
BottleNeck.6.conv2.1.weight
BottleNeck.6.conv2.1.bias
BottleNeck.6.style2.linear.weight
BottleNeck.6.style2.linear.bias
BottleNeck.6.style2.conv_ada1.weight
BottleNeck.6.style2.conv_ada1.bias
BottleNeck.6.style2.bn_ada1.weight
BottleNeck.6.style2.bn_ada1.bias
BottleNeck.6.style2.bn_ada1.running_mean
BottleNeck.6.style2.bn_ada1.running_var
BottleNeck.6.style2.bn_ada1.num_batches_tracked
BottleNeck.6.style2.conv_ada2.weight
BottleNeck.6.style2.conv_ada2.bias
BottleNeck.7.conv1.1.weight
BottleNeck.7.conv1.1.bias
BottleNeck.7.style1.linear.weight
BottleNeck.7.style1.linear.bias
BottleNeck.7.style1.conv_ada1.weight
BottleNeck.7.style1.conv_ada1.bias
BottleNeck.7.style1.bn_ada1.weight
BottleNeck.7.style1.bn_ada1.bias
BottleNeck.7.style1.bn_ada1.running_mean
BottleNeck.7.style1.bn_ada1.running_var
BottleNeck.7.style1.bn_ada1.num_batches_tracked
BottleNeck.7.style1.conv_ada2.weight
BottleNeck.7.style1.conv_ada2.bias
BottleNeck.7.conv2.1.weight
BottleNeck.7.conv2.1.bias
BottleNeck.7.style2.linear.weight
BottleNeck.7.style2.linear.bias
BottleNeck.7.style2.conv_ada1.weight
BottleNeck.7.style2.conv_ada1.bias
BottleNeck.7.style2.bn_ada1.weight
BottleNeck.7.style2.bn_ada1.bias
BottleNeck.7.style2.bn_ada1.running_mean
BottleNeck.7.style2.bn_ada1.running_var
BottleNeck.7.style2.bn_ada1.num_batches_tracked
BottleNeck.7.style2.conv_ada2.weight
BottleNeck.7.style2.conv_ada2.bias
BottleNeck.8.conv1.1.weight
BottleNeck.8.conv1.1.bias
BottleNeck.8.style1.linear.weight
BottleNeck.8.style1.linear.bias
BottleNeck.8.style1.conv_ada1.weight
BottleNeck.8.style1.conv_ada1.bias
BottleNeck.8.style1.bn_ada1.weight
BottleNeck.8.style1.bn_ada1.bias
BottleNeck.8.style1.bn_ada1.running_mean
BottleNeck.8.style1.bn_ada1.running_var
BottleNeck.8.style1.bn_ada1.num_batches_tracked
BottleNeck.8.style1.conv_ada2.weight
BottleNeck.8.style1.conv_ada2.bias
BottleNeck.8.conv2.1.weight
BottleNeck.8.conv2.1.bias
BottleNeck.8.style2.linear.weight
BottleNeck.8.style2.linear.bias
BottleNeck.8.style2.conv_ada1.weight
BottleNeck.8.style2.conv_ada1.bias
BottleNeck.8.style2.bn_ada1.weight
BottleNeck.8.style2.bn_ada1.bias
BottleNeck.8.style2.bn_ada1.running_mean
BottleNeck.8.style2.bn_ada1.running_var
BottleNeck.8.style2.bn_ada1.num_batches_tracked
BottleNeck.8.style2.conv_ada2.weight
BottleNeck.8.style2.conv_ada2.bias
up3.1.weight
up3.1.bias
up3.2.weight
up3.2.bias
up3.2.running_mean
up3.2.running_var
up3.2.num_batches_tracked
up2.1.weight
up2.1.bias
up2.2.weight
up2.2.bias
up2.2.running_mean
up2.2.running_var
up2.2.num_batches_tracked
up1.1.weight
up1.1.bias
up1.2.weight
up1.2.bias
up1.2.running_mean
up1.2.running_var
up1.2.num_batches_tracked
up0.1.weight
up0.1.bias
up0.2.weight
up0.2.bias
up0.2.running_mean
up0.2.running_var
up0.2.num_batches_tracked
last_layer.1.weight
last_layer.1.bias
'''