model:
  name: Recce
  num_classes: 1
config:
  lambda_1: 0.1
  lambda_2: 0.1
  optimizer:
    name: adam
    lr: 0.0002
    weight_decay: 0.00001
  scheduler:
    name: StepLR
    step_size: 22500
    gamma: 0.5
  resume: False
  resume_best: False
  id: FF++c40
  loss: binary_ce
  metric: Acc
  debug: False
  epoch: 5 # TODO
  device: "cuda:1" # TODO
  log_path: './log.txt'
  #  ckpt: best_model_1000
  # warmup_step: 0
data:
  train_batch_size: 100
  val_batch_size: 200
  test_batch_size: 200
  name: Custom_Deepfake
  file: "./config/dataset/custom_deepfake.yml"
  train_branch: "train_cfg"
  val_branch: "test_cfg"
  test_branch: "test_cfg"
